package com.sofittech.soccerballjerseymaker;

import android.graphics.Color;
import android.support.v4.media.TransportMediator;
import android.support.v4.view.InputDeviceCompat;
import android.support.v4.view.MotionEventCompat;
import android.support.v7.widget.helper.ItemTouchHelper.Callback;
import java.util.HashMap;

public class Utils {
    public static String[] Algeria;
    public static int[] AlgeriaColor;
    public static int[] AlgeriaShirts;
    public static String[] Argentina;
    public static int[] ArgentinaColor;
    public static int[] ArgentinaShirts;
    public static String[] Australia;
    public static int[] AustraliaColor;
    public static int[] AustraliaShirts;
    public static String[] Austria;
    public static int[] AustriaColor;
    public static int[] AustriaShirts;
    public static String[] Belgium;
    public static int[] BelgiumColor;
    public static int[] BelgiumShirts;
    public static String[] Bolivia;
    public static int[] BoliviaColor;
    public static int[] BoliviaShirts;
    public static String[] Bosnia;
    public static int[] BosniaColor;
    public static int[] BosniaShirts;
    public static String[] Brasil;
    public static int[] BrasilColor;
    public static int[] BrasilShirts;
    public static String[] Chile;
    public static int[] ChileColor;
    public static int[] ChileShirts;
    public static HashMap<Integer, String[]> Clubs;
    public static String[] Colombia;
    public static int[] ColombiaColor;
    public static int[] ColombiaShirts;
    public static HashMap<Integer, int[]> Colors;
    public static String[] Costa_Rica;
    public static int[] Costa_RicaColor;
    public static int[] Costa_RicaShirts;
    public static String[] Czech_Republic;
    public static int[] Czech_RepublicColor;
    public static int[] Czech_RepublicShirts;
    public static String[] Denmark;
    public static int[] DenmarkColor;
    public static int[] DenmarkShirts;
    public static String[] Ecuador;
    public static int[] EcuadorColor;
    public static int[] EcuadorShirts;
    public static String[] Egypt;
    public static int[] EgyptColor;
    public static int[] EgyptShirts;
    public static String[] England;
    public static int[] EnglandColor;
    public static int[] EnglandShirts;
    public static String[] France;
    public static int[] FranceColor;
    public static int[] FranceShirts;
    public static String[] Germany;
    public static int[] GermanyColor;
    public static int[] GermanyShirts;
    public static String[] Indonesia;
    public static int[] IndonesiaColor;
    public static int[] IndonesiaShirts;
    public static String[] Italy;
    public static int[] ItalyColor;
    public static int[] ItalyShirts;
    public static String[] Malaysia;
    public static int[] MalaysiaColor;
    public static int[] MalaysiaShirts;
    public static String[] Mexico;
    public static int[] MexicoColor;
    public static int[] MexicoShirts;
    public static String[] Netherland;
    public static int[] NetherlandColor;
    public static int[] NetherlandShirts;
    public static String[] Nigeria;
    public static int[] NigeriaColor;
    public static int[] NigeriaShirts;
    public static String[] Peru;
    public static int[] PeruColor;
    public static int[] PeruShirts;
    public static String[] Poland;
    public static int[] PolandColor;
    public static int[] PolandShirts;
    public static String[] Portugal;
    public static int[] PortugalColor;
    public static int[] PortugalShirts;
    public static String[] Russia;
    public static int[] RussiaColor;
    public static int[] RussiaShirts;
    public static String[] Saudi_Arabia;
    public static int[] Saudi_ArabiaColor;
    public static int[] Saudi_ArabiaShirts;
    public static HashMap<Integer, int[]> Shirts;
    public static String[] Spain;
    public static int[] SpainColor;
    public static int[] SpainShirts;
    public static String[] Sweden;
    public static int[] SwedenColor;
    public static int[] SwedenShirts;
    public static String[] Switzerland;
    public static int[] SwitzerlandColor;
    public static int[] SwitzerlandShirts;
    public static String[] Turkey;
    public static int[] TurkeyColor;
    public static int[] TurkeyShirts;
    public static String[] United_States;
    public static int[] United_StatesColor;
    public static int[] United_StatesShirts;
    public static String[] Uruguay;
    public static int[] UruguayColor;
    public static int[] UruguayShirts;
    public static String[] Venezuela;
    public static int[] VenezuelaColor;
    public static int[] VenezuelaShirts;
    public static String[] Wales;
    public static int[] WalesColor;
    public static int[] WalesShirts;
    public static int[] count;
    public static int isFristTime;

    static {
        isFristTime = 0;
        Algeria = new String[]{"Algeria"};
        AlgeriaShirts = new int[]{R.drawable.alg_algeria};
        AlgeriaColor = new int[]{Color.rgb(16, R.styleable.AppCompatTheme_buttonStyle, 75)};
        Argentina = new String[]{"Argentina", "Boca Juniors", "Estudiantes", "Independiente", "Racing Club", "River Plate", "Rosario Central", "San Lorenzo", "Velez Sarsfield"};
        ArgentinaShirts = new int[]{R.drawable.arg_argentina, R.drawable.arg_boca_juniors, R.drawable.arg_estudiantes, R.drawable.arg_independiente, R.drawable.agr_racing_club, R.drawable.arg_river_plate, R.drawable.arg_rosario_central, R.drawable.arg_san_lorenzo, R.drawable.arg_velez_sarsfield};
        ArgentinaColor = new int[]{Color.rgb(0, 0, 0), Color.rgb(242, 245, 242), Color.rgb(48, 48, 48), Color.rgb(252, 252, 252), Color.rgb(0, 0, 0), Color.rgb(42, 42, 42), Color.rgb(251, 251, 251), Color.rgb(225, 225, 225), Color.rgb(247, 247, 247)};
        Australia = new String[]{"Australia"};
        AustraliaShirts = new int[]{R.drawable.aus_australia};
        AustraliaColor = new int[]{Color.rgb(10, 66, 38)};
        Austria = new String[]{"Austria"};
        AustriaShirts = new int[]{R.drawable.aust_austria};
        AustriaColor = new int[]{Color.rgb(242, 240, 241)};
        Belgium = new String[]{"Belgium"};
        BelgiumShirts = new int[]{R.drawable.bel_belgium};
        BelgiumColor = new int[]{Color.rgb(211, 210, 17)};
        Bolivia = new String[]{"Bolivia"};
        BoliviaShirts = new int[]{R.drawable.bol_bolivia};
        BoliviaColor = new int[]{Color.rgb(248, 249, 249)};

        Bosnia = new String[]{"Bosnia"};
        BosniaShirts = new int[]{R.drawable.bos_bosnia};
        BosniaColor = new int[]{Color.rgb(229, 205, 55)};
        Brasil = new String[]{"Brasil", "Atletico Mineiro", "Bayer", "Corinthians", "Cruzeiro", "Flamengo", "Fluminense", "Internacional", "Palmeiras", "Santos FC"};
        BrasilShirts = new int[]{R.drawable.bra_brazil, R.drawable.bra_atletico_mineiro, R.drawable.bra_bayer, R.drawable.bra_corinthians, R.drawable.bra_cruzeiro, R.drawable.bra_flamengo, R.drawable.bra_fluminense, R.drawable.bra_internacional, R.drawable.bra_palmeiras, R.drawable.bra_santos_fc};
        BrasilColor = new int[]{Color.rgb(0, 96, 44), Color.rgb(22, 22, 22), Color.rgb(228, 228, 228), Color.rgb(0, 0, 0), Color.rgb(Callback.DEFAULT_SWIPE_ANIMATION_DURATION, 251, 248), Color.rgb(MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK), Color.rgb(233, 233, 233), Color.rgb(246, 246, 246), Color.rgb(226, 226, 226), Color.rgb(95, 95, 97)};
        Chile = new String[]{"Chile", "Colo Colo", "Universidad catolica", "Universidad de chile"};
        ChileShirts = new int[]{R.drawable.chi_chile, R.drawable.chi_colo_colo, R.drawable.chi_universidad_catolica, R.drawable.chi_universidad_de_chile};
        ChileColor = new int[]{Color.rgb(244, 241, 240), Color.rgb(0, 0, 0), Color.rgb(219, 0, 20), Color.rgb(221, 221, 221)};
        Colombia = new String[]{"Colombia", "America De Cali", "Atletico Nacional", "Deportivo Cali", "Millonarios FC", "Santa Fe"};
        ColombiaShirts = new int[]{R.drawable.col_colombia, R.drawable.col_america_de_cali, R.drawable.col_atletico_nacional, R.drawable.col_deportivo_cali, R.drawable.col_millonarios_fc, R.drawable.col_santa_fe};
        ColombiaColor = new int[]{Color.rgb(36, 38, 75), Color.rgb(229, 227, 227), Color.rgb(172, 223, 182), Color.rgb(253, 253, 253), Color.rgb(231, 231, 228), Color.rgb(249, 249, 249)};
        Costa_Rica = new String[]{"Costa Rica", "Deportivo Saprissa"};
        Costa_RicaShirts = new int[]{R.drawable.cos_costa_rica, R.drawable.cos_deportivo_saprissa};
        Costa_RicaColor = new int[]{Color.rgb(169, TransportMediator.KEYCODE_MEDIA_PLAY, 51), Color.rgb(140, 148, 150)};
        Czech_Republic = new String[]{"Czech Republic"};
        Czech_RepublicShirts = new int[]{R.drawable.cze_czech_republic};
        Czech_RepublicColor = new int[]{Color.rgb(148, 148, 148)};
        Denmark = new String[]{"Denmark"};
        DenmarkShirts = new int[]{R.drawable.den_denmark};
        DenmarkColor = new int[]{Color.rgb(251, 251, 251)};
        Ecuador = new String[]{"Ecuador", "Emelec"};
        EcuadorShirts = new int[]{R.drawable.ecu_ecuador, R.drawable.ecu_emelec};
        EcuadorColor = new int[]{Color.rgb(5, 35, 63), Color.rgb(183, 178, 171)};
        Egypt = new String[]{"Egypt"};
        EgyptShirts = new int[]{R.drawable.egy_egypt};
        EgyptColor = new int[]{Color.rgb(243, 243, 243)};
        England = new String[]{"England", "Arsenal", "Chelsea", "Celtic", "Liverpool", "Manchester City", "Manchester United", "Tottenham"};
        EnglandShirts = new int[]{R.drawable.eng_england, R.drawable.eng_arsenal, R.drawable.eng_chelsea, R.drawable.eng_celtic, R.drawable.eng_liver_pool, R.drawable.eng_manchester_city, R.drawable.eng_manchester_united, R.drawable.eng_tottenham};
        EnglandColor = new int[]{Color.rgb(0, 62, 146), Color.rgb(252, 252, 252), Color.rgb(MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK), Color.rgb(37, 35, 35), Color.rgb(252, 252, 252), Color.rgb(15, 3, 77), Color.rgb(254, 254, 254), Color.rgb(17, 33, 70)};
        France = new String[]{"France", "Marseille", "Olympique Lyon", "PSG"};
        FranceShirts = new int[]{R.drawable.fra_france, R.drawable.fra_marseille, R.drawable.fra_olympique_lyon, R.drawable.fra_psg};
        FranceColor = new int[]{Color.rgb(234, 234, 234), Color.rgb(0, 160, 220), Color.rgb(10, 54, 137), Color.rgb(253, 254, 254)};
        Germany = new String[]{"Germany", "Bayer", "Bayern Munchen", "Dortmund", "Werder Bremen", "wolfsburg"};
        GermanyShirts = new int[]{R.drawable.ger_germany, R.drawable.ger_bayer, R.drawable.ger_bayern_munchen, R.drawable.ger_dortmund, R.drawable.ger_werder_bremen, R.drawable.ger_wolfsburg};
        GermanyColor = new int[]{Color.rgb(0, 0, 0), Color.rgb(MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK), Color.rgb(251, 251, 251), Color.rgb(0, 0, 0), Color.rgb(MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK), Color.rgb(85, 177, 59)};
        Indonesia = new String[]{"Indonesia"};
        IndonesiaShirts = new int[]{R.drawable.ind_indonesia};
        IndonesiaColor = new int[]{Color.rgb(MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK)};
        Italy = new String[]{"Ac Milan", "As Roma", "Fiorentina", "Internazionale", "Italia Euro", "Juventus FC", "SS lazio", "SSC Napoli"};
        ItalyShirts = new int[]{R.drawable.ita_ac_milan, R.drawable.ita_as_roma, R.drawable.ita_fiorentina, R.drawable.ita_internazionale, R.drawable.ita_italia, R.drawable.ita_juventus, R.drawable.ita_ss_lazio, R.drawable.ita_ssc_napoli};
        ItalyColor = new int[]{Color.rgb(227, 226, 218), Color.rgb(238, 141, 24), Color.rgb(Callback.DEFAULT_SWIPE_ANIMATION_DURATION, Callback.DEFAULT_SWIPE_ANIMATION_DURATION, Callback.DEFAULT_SWIPE_ANIMATION_DURATION), Color.rgb(225, 213, 39), Color.rgb(242, 240, 238), Color.rgb(1, 1, 1), Color.rgb(254, 254, 254), Color.rgb(251, 251, 251)};
        Malaysia = new String[]{"Malaysia"};
        MalaysiaShirts = new int[]{R.drawable.mal_malaysia};
        MalaysiaColor = new int[]{Color.rgb(1, 1, 1)};
        Mexico = new String[]{"Mexico", "Atlas", "Club America", "Cruz Azul", "Guadalajara", "Monterrey", "Pumas Unam", "Tigres Uanl", "Toluca FC"};
        MexicoShirts = new int[]{R.drawable.mex_mexico, R.drawable.mex_atlas, R.drawable.mex_club_america, R.drawable.mex_cruz_azul, R.drawable.mex_guadalajara, R.drawable.mex_monterrey, R.drawable.mex_pumas_unam, R.drawable.mex_tigres_uanl, R.drawable.mex_toluca};
        MexicoColor = new int[]{Color.rgb(254, 254, 254), Color.rgb(237, 237, 237), Color.rgb(0, 39, 63), Color.rgb(246, 251, MotionEventCompat.ACTION_MASK), Color.rgb(246, 251, MotionEventCompat.ACTION_MASK), Color.rgb(26, 26, 26), Color.rgb(52, 43, 74), Color.rgb(31, 65, 138), Color.rgb(248, 242, 242)};
        Netherland = new String[]{"Netherland", "AFC ajax", "Feyenoord", "Psv"};
        NetherlandShirts = new int[]{R.drawable.net_netherland, R.drawable.net_afc_ajax, R.drawable.net_fayenoord, R.drawable.net_psv};
        NetherlandColor = new int[]{Color.rgb(15, 45, 143), Color.rgb(MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK, MotionEventCompat.ACTION_MASK), Color.rgb(0, 0, 0), Color.rgb(11, 9, 13)};
        Nigeria = new String[]{"Nigeria"};
        NigeriaShirts = new int[]{R.drawable.nig_nigeria};
        NigeriaColor = new int[]{Color.rgb(Callback.DEFAULT_SWIPE_ANIMATION_DURATION, Callback.DEFAULT_SWIPE_ANIMATION_DURATION, 247)};
        Peru = new String[]{"Peru", "Club Alianza Lima", "Sporting Cristal", "Universitario"};
        PeruShirts = new int[]{R.drawable.per_peru, R.drawable.per_club_alianza, R.drawable.per_sporting_cristal, R.drawable.per_universitario};
        PeruColor = new int[]{Color.rgb(10, 10, 10), Color.rgb(243, 50, 43), Color.rgb(234, 236, 235), Color.rgb(190, 3, 46)};
        Poland = new String[]{"Poland"};
        PolandShirts = new int[]{R.drawable.pol_polska};
        PolandColor = new int[]{Color.rgb(Callback.DEFAULT_DRAG_ANIMATION_DURATION, 22, 44)};
        Portugal = new String[]{"Portugal", "FC porto", "SL Benfica", "Sportinf CP"};
        PortugalShirts = new int[]{R.drawable.por_portugal, R.drawable.por_fc_porto, R.drawable.por_si_benfica, R.drawable.por_sportinf_cp};
        PortugalColor = new int[]{Color.rgb(248, 248, 248), Color.rgb(230, 230, 230), Color.rgb(248, 248, 248), Color.rgb(248, 248, 248)};
        Russia = new String[]{"Russia"};
        RussiaShirts = new int[]{R.drawable.rus_russia};
        RussiaColor = new int[]{Color.rgb(218, 180, 99)};
        Saudi_Arabia = new String[]{"Saudi Arabia"};
        Saudi_ArabiaShirts = new int[]{R.drawable.sau_saudia_arabia};
        Saudi_ArabiaColor = new int[]{Color.rgb(20, 77, 24)};
        Spain = new String[]{"Spain", "Athletic Bilbao", "Atletico Madrid", "Barcelona FC", "Fc barcelona", "Real Madrid", "Real Sociedad", "Sevilla", "Valencia"};
        SpainShirts = new int[]{R.drawable.spa_spain, R.drawable.spa_athletic_bilbao, R.drawable.spa_atletico_madrid, R.drawable.spa_barcelona, R.drawable.spa_fc_barcelona, R.drawable.spa_real_madrid, R.drawable.spa_real_sociedad, R.drawable.spa_sevilla, R.drawable.spa_valencia};
        SpainColor = new int[]{Color.rgb(230, 216, 4), Color.rgb(Callback.DEFAULT_DRAG_ANIMATION_DURATION, 199, 203), Color.rgb(1, 70, 150), Color.rgb(0, 0, 0), Color.rgb(230, 190, 6), Color.rgb(34, 48, 87), Color.rgb(0, 0, 0), Color.rgb(203, 0, 28), Color.rgb(0, 0, 0)};
        Sweden = new String[]{"Sweden"};
        SwedenShirts = new int[]{R.drawable.swe_sweden};
        SwedenColor = new int[]{Color.rgb(2, 77, 160)};
        Switzerland = new String[]{"Switzerland"};
        SwitzerlandShirts = new int[]{R.drawable.swi_switzerland};
        SwitzerlandColor = new int[]{Color.rgb(InputDeviceCompat.SOURCE_KEYBOARD, InputDeviceCompat.SOURCE_KEYBOARD, InputDeviceCompat.SOURCE_KEYBOARD)};
        Turkey = new String[]{"Turkey", "Besiktas", "Fenerbahce", "Galatasaray"};
        TurkeyShirts = new int[]{R.drawable.tur_turkey, R.drawable.tur_besiktas, R.drawable.tur_fenerbahce, R.drawable.tur_galatasaray};
        TurkeyColor = new int[]{Color.rgb(245, 245, 245), Color.rgb(0, 0, 0), Color.rgb(245, 245, 245), Color.rgb(245, 245, 245)};
        Uruguay = new String[]{"Uruguay"};
        UruguayShirts = new int[]{R.drawable.uru_uruguay};
        UruguayColor = new int[]{Color.rgb(0, 0, 0)};
        United_States = new String[]{"United States", "La Galaxy"};
        United_StatesShirts = new int[]{R.drawable.usa_united_states, R.drawable.usa_la_galaxy};
        United_StatesColor = new int[]{Color.rgb(0, 15, 40), Color.rgb(0, 15, 40)};
        Venezuela = new String[]{"Venezuela"};
        VenezuelaShirts = new int[]{R.drawable.ven_venezuela};
        VenezuelaColor = new int[]{Color.rgb(TransportMediator.KEYCODE_MEDIA_PLAY, 168, 20)};
        Wales = new String[]{"Wales"};
        WalesShirts = new int[]{R.drawable.wal_wales};
        WalesColor = new int[]{Color.rgb(252, 252, 252)};
        count = new int[]{1, 9, 1, 1, 1, 1, 1, 10, 4, 6, 2, 1, 1, 2, 1, 8, 4, 6, 1, 8, 1, 9, 4, 1, 4, 1, 4, 1, 1, 9, 1, 1, 4, 1, 2, 1, 1};
        Colors = new HashMap();
        Colors.put(Integer.valueOf(0), AlgeriaColor);
        Colors.put(Integer.valueOf(1), ArgentinaColor);
        Colors.put(Integer.valueOf(2), AustraliaColor);
        Colors.put(Integer.valueOf(3), AustriaColor);
        Colors.put(Integer.valueOf(4), BelgiumColor);
        Colors.put(Integer.valueOf(5), BoliviaColor);
        Colors.put(Integer.valueOf(6), BosniaColor);
        Colors.put(Integer.valueOf(7), BrasilColor);
        Colors.put(Integer.valueOf(8), ChileColor);
        Colors.put(Integer.valueOf(9), ColombiaColor);
        Colors.put(Integer.valueOf(10), Costa_RicaColor);
        Colors.put(Integer.valueOf(11), Czech_RepublicColor);
        Colors.put(Integer.valueOf(12), DenmarkColor);
        Colors.put(Integer.valueOf(13), EcuadorColor);
        Colors.put(Integer.valueOf(14), EgyptColor);
        Colors.put(Integer.valueOf(15), EnglandColor);
        Colors.put(Integer.valueOf(16), FranceColor);
        Colors.put(Integer.valueOf(17), GermanyColor);
        Colors.put(Integer.valueOf(18), IndonesiaColor);
        Colors.put(Integer.valueOf(19), ItalyColor);
        Colors.put(Integer.valueOf(20), MalaysiaColor);
        Colors.put(Integer.valueOf(21), MexicoColor);
        Colors.put(Integer.valueOf(22), NetherlandColor);
        Colors.put(Integer.valueOf(23), NigeriaColor);
        Colors.put(Integer.valueOf(24), PeruColor);
        Colors.put(Integer.valueOf(25), PolandColor);
        Colors.put(Integer.valueOf(26), PortugalColor);
        Colors.put(Integer.valueOf(27), RussiaColor);
        Colors.put(Integer.valueOf(28), Saudi_ArabiaColor);
        Colors.put(Integer.valueOf(29), SpainColor);
        Colors.put(Integer.valueOf(30), SwedenColor);
        Colors.put(Integer.valueOf(31), SwitzerlandColor);
        Colors.put(Integer.valueOf(32), TurkeyColor);
        Colors.put(Integer.valueOf(33), UruguayColor);
        Colors.put(Integer.valueOf(34), United_StatesColor);
        Colors.put(Integer.valueOf(35), VenezuelaColor);
        Colors.put(Integer.valueOf(36), WalesColor);
        Shirts = new HashMap();
        Shirts.put(Integer.valueOf(0), AlgeriaShirts);
        Shirts.put(Integer.valueOf(1), ArgentinaShirts);
        Shirts.put(Integer.valueOf(2), AustraliaShirts);
        Shirts.put(Integer.valueOf(3), AustriaShirts);
        Shirts.put(Integer.valueOf(4), BelgiumShirts);
        Shirts.put(Integer.valueOf(5), BoliviaShirts);
        Shirts.put(Integer.valueOf(6), BosniaShirts);
        Shirts.put(Integer.valueOf(7), BrasilShirts);
        Shirts.put(Integer.valueOf(8), ChileShirts);
        Shirts.put(Integer.valueOf(9), ColombiaShirts);
        Shirts.put(Integer.valueOf(10), Costa_RicaShirts);
        Shirts.put(Integer.valueOf(11), Czech_RepublicShirts);
        Shirts.put(Integer.valueOf(12), DenmarkShirts);
        Shirts.put(Integer.valueOf(13), EcuadorShirts);
        Shirts.put(Integer.valueOf(14), EgyptShirts);
        Shirts.put(Integer.valueOf(15), EnglandShirts);
        Shirts.put(Integer.valueOf(16), FranceShirts);
        Shirts.put(Integer.valueOf(17), GermanyShirts);
        Shirts.put(Integer.valueOf(18), IndonesiaShirts);
        Shirts.put(Integer.valueOf(19), ItalyShirts);
        Shirts.put(Integer.valueOf(20), MalaysiaShirts);
        Shirts.put(Integer.valueOf(21), MexicoShirts);
        Shirts.put(Integer.valueOf(22), NetherlandShirts);
        Shirts.put(Integer.valueOf(23), NigeriaShirts);
        Shirts.put(Integer.valueOf(24), PeruShirts);
        Shirts.put(Integer.valueOf(25), PolandShirts);
        Shirts.put(Integer.valueOf(26), PortugalShirts);
        Shirts.put(Integer.valueOf(27), RussiaShirts);
        Shirts.put(Integer.valueOf(28), Saudi_ArabiaShirts);
        Shirts.put(Integer.valueOf(29), SpainShirts);
        Shirts.put(Integer.valueOf(30), SwedenShirts);
        Shirts.put(Integer.valueOf(31), SwitzerlandShirts);
        Shirts.put(Integer.valueOf(32), TurkeyShirts);
        Shirts.put(Integer.valueOf(33), UruguayShirts);
        Shirts.put(Integer.valueOf(34), United_StatesShirts);
        Shirts.put(Integer.valueOf(35), VenezuelaShirts);
        Shirts.put(Integer.valueOf(36), WalesShirts);
        Clubs = new HashMap();
        Clubs.put(Integer.valueOf(0), Algeria);
        Clubs.put(Integer.valueOf(1), Argentina);
        Clubs.put(Integer.valueOf(2), Australia);
        Clubs.put(Integer.valueOf(3), Austria);
        Clubs.put(Integer.valueOf(4), Belgium);
        Clubs.put(Integer.valueOf(5), Bolivia);
        Clubs.put(Integer.valueOf(6), Bosnia);
        Clubs.put(Integer.valueOf(7), Brasil);
        Clubs.put(Integer.valueOf(8), Chile);
        Clubs.put(Integer.valueOf(9), Colombia);
        Clubs.put(Integer.valueOf(10), Costa_Rica);
        Clubs.put(Integer.valueOf(11), Czech_Republic);
        Clubs.put(Integer.valueOf(12), Denmark);
        Clubs.put(Integer.valueOf(13), Ecuador);
        Clubs.put(Integer.valueOf(14), Egypt);
        Clubs.put(Integer.valueOf(15), England);
        Clubs.put(Integer.valueOf(16), France);
        Clubs.put(Integer.valueOf(17), Germany);
        Clubs.put(Integer.valueOf(18), Indonesia);
        Clubs.put(Integer.valueOf(19), Italy);
        Clubs.put(Integer.valueOf(20), Malaysia);
        Clubs.put(Integer.valueOf(21), Mexico);
        Clubs.put(Integer.valueOf(22), Netherland);
        Clubs.put(Integer.valueOf(23), Nigeria);
        Clubs.put(Integer.valueOf(24), Peru);
        Clubs.put(Integer.valueOf(25), Poland);
        Clubs.put(Integer.valueOf(26), Portugal);
        Clubs.put(Integer.valueOf(27), Russia);
        Clubs.put(Integer.valueOf(28), Saudi_Arabia);
        Clubs.put(Integer.valueOf(29), Spain);
        Clubs.put(Integer.valueOf(30), Sweden);
        Clubs.put(Integer.valueOf(31), Switzerland);
        Clubs.put(Integer.valueOf(32), Turkey);
        Clubs.put(Integer.valueOf(33), Uruguay);
        Clubs.put(Integer.valueOf(34), United_States);
        Clubs.put(Integer.valueOf(35), Venezuela);
        Clubs.put(Integer.valueOf(36), Wales);
    }

    public static HashMap<Integer, String[]> getClubs() {
        return Clubs;
    }

    public static HashMap<Integer, int[]> getShirts() {
        return Shirts;
    }

    public static HashMap<Integer, int[]> getColors() {
        return Colors;
    }
}

